spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/govey"
    username: "govey"
    password: "goveydb"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernateformat_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    defer-datasource-initialization: true
  profiles:
    active: ${PROFILE_ACTIVE}
  sql:
    init:
      mode: always
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 101536000

server:
  error:
    include-message: always