spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernateformat_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: NEVER
server:
    error:
      include-message: always