spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: "jdbc:postgresql://localhost:5432/govey"
    username: "govey"
    password: "goveydb"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernateformat_sql: true
  profiles:
    active: ${PROFILE_ACTIVE}

server:
  error:
    include-message: always