spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/govey"
    username: "govey"
    password: "goveydb"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernateformat_sql: true
    defer-datasource-initialization: true
  profiles:
    active: ${PROFILE_ACTIVE}
    include: oauth
  sql:
    init:
      mode: always

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

server:
  error:
    include-message: always