spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 'CLIENT-KEY'
            clientSecret: 'CLIENT-SECRETS'
            scope:
              - email
              - profile